{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-sample-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-sample-chart.labels" . | nindent 4 }}
  {{- if .Values.sia.enabled }}
  annotations:
    {{- if ne .Values.eks.roleName "" }}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.eks.accountId }}:role/{{ .Values.eks.roleName }}"
    {{- end }}
    {{- if ne .Values.gke.gsa "" }}
    iam.gke.io/gcp-service-account: {{ .Values.gke.gsa }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}